apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1
  - name: PostgreSQL MECHA
    orgId: 1

datasources:
  - name: PostgreSQL MECHA
    uid: mecha-postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    database: mecha_db
    user: mecha_user
    isDefault: true
    editable: false
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
